### ISSUE TITLE
[Feature request]: Changing the .dll path

### ISSUE THREAD

**Issue by mrjshzk** [vaporvee/discord-sdk-godot#30]
### What is your idea?

First of all, thank you for your patience,

Is there any way to change to path for the dll when a project is exported?
I don't mind building the addon from source to make the change.

My reasoning for this is, since I use the .Net version of Godot, I would put the dll's inside the folder that contains .net/C# dll's and make the folder for the project cleaner

![image](https://github.com/vaporvee/discord-sdk-godot/assets/115943663/74c75543-18dd-4f7a-999f-e54a0bf8c87e)

**Comment by vaporvee** [comment]
No sorry thats an issue for the engine github repo. i cant change where the exporter puts the files because the exe needs the file in the place where the engine wants it. but i would use the native c# discord sdk anyway

**Comment by mrjshzk** [comment]
Thank you very much for your patience! What do you mean by the native C# Discord sdk, [this](https://discord.com/developers/docs/game-sdk/sdk-starter-guide)?

**Comment by vaporvee** [comment]
Yeah I meant this! I'm really sorry forgot to answer :/
You could also just install the nuget package (its a bit older but still works)
And big news since my plugin reached 2.3 you can edit the following file like i would do
https://github.com/vaporvee/discord-sdk-godot/blob/main/project/addons/discord-sdk-gd/discord-rpc-gd.gdextension

```cfg

[configuration]

entry_symbol = "discordsdkgd_library_init"

[libraries]

windows.debug.x86_64 = { "bin/windows/discord_game_sdk_binding_debug.dll": "data_game_x86_64/" }
windows.release.x86_64 = { "bin/windows/discord_game_sdk_binding.dll": "data_game_x86_64/" }
(other stuff...)

[dependencies]


windows.debug.x86_64 = { "bin/windows/discord_game_sdk.dll": "data_game_x86_64/" }
windows.release.x86_64 = { "bin/windows/discord_game_sdk.dll": "data_game_x86_64/" }
(other stuff...)
```
I'm not sure if that even works didn't test it tbh but the contributer in #31 said that it could work like that

**Comment by vaporvee** [comment]
@mrjshzk

**Comment by mrjshzk** [comment]
I'll check it out tomorrow when I have time
Thank you!
